name: Validate-YAML

on:
  pull_request:
    paths:
      - 'embeds.yml'
    types: 
      - opened
      - reopened
      - synchronize

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate YAML file
        run: yamllint -c .yamllint embeds.yml
